# --- Game ---
WIDTH, HEIGHT = 800, 600

RESET_TIME_ROUNDS = 2500
RESET_TIME_GAME = 5000

# --- Paddle ---
PADDLE_WIDTH, PADDLE_HEIGHT = 36, 16
PADDLE_COLOR = (34, 106, 230)
PADDLE_SPEED = 250

# --- Wall ---
WALL_THICKNESS = 12
OFFSET_Y = 64
OFFSET_X = 170
WALL_COLOR = (255, 255, 255)

# --- Bricks ---
BRICKS_ROW = 14
BRICK_COLS = 8
ROWS_PER_COLOR = 2
MARGIN_X = OFFSET_X + WALL_THICKNESS
MARGIN_Y = OFFSET_Y + WALL_THICKNESS + 76

BRICK_COLORS = [(235, 27, 12), (232, 132, 9), (12, 235, 45), (231, 235, 12)]
BRICK_HEIGHT = 12
BRICK_WIDTH = 32

# --- Ball ---
BALL_HEIGHT = 6
BALL_WIDTH = 10
BALL_COLOR = ((255, 255, 255))

BALL_START_Y = 360
BALL_START_SPEED = 200

# --- User Interface ---
FONT_SIZE = int((MARGIN_Y - OFFSET_Y) / 2 - WALL_THICKNESS)

LEVEL_POS_X = OFFSET_X + WALL_THICKNESS
LEVEL_POS_Y = OFFSET_Y + WALL_THICKNESS

SCORE_POS_X = LEVEL_POS_X + 4 * FONT_SIZE
SCORE_POS_Y = LEVEL_POS_Y + FONT_SIZE

LIVES_POS_X = OFFSET_X + WALL_THICKNESS + BRICK_WIDTH * 8
LIVES_POS_Y = LEVEL_POS_Y

HIGH_SCORE_POS_X = LIVES_POS_X + 4 * FONT_SIZE
HIGH_SCORE_POS_Y = LEVEL_POS_Y + FONT_SIZE